### PR TITLE
WL-3356 Don’t leak memory when indexing PDFs.

### PR DESCRIPTION
**Pull request by buckett**
PDFBox keeps a cache of something todo with fonts and over time this just accumulates heap. To work around this we clear out the cache after indexing each document. I’ve also bumped up the version of PDFBox to the latest version.

### CODE REVIEW

**Comment by ghost** [comment]
This won't significantly slow down PDFBox if it has to fetch fonts every time?

**Comment by ghost** [comment]
Also I'm assuming the version change isn't a risky one.

**Comment by buckett** [comment]
I'd believe there will be a performance hit, but while parsing the PDF it should be cached most of the time. CMap files are for having different text presented compared to what is displayed. http://blog.idrsolutions.com/2012/05/understanding-the-pdf-file-format-embedded-cmap-tables/

I would imaging that this is normally pretty specific to each file being parsed. Running out of memory is much more of a problem that slow PDF parsing so even if it is slow I'd rather have that problem and then we can look at speeding it up if we need to.

**Comment by ghost** [comment]
Good :+1: Thanks for the explanation.

**Pull request merged**
